export const SOLUTIONS = [
  {
    slug: 'healthcare',
    name: 'Healthcare',
    eyebrow: 'Clinics, dental, and care groups',
    title: 'AI voice agents for healthcare that patients actually want to talk to',
    description:
      'Answer every appointment, triage, and after-hours call with HIPAA-ready voice AI. VoilitAI books visits, captures intake, and escalates emergencies without adding headcount.',
    metric: '78%',
    metricLabel: 'shorter wait times',
    pain: 'Front desks miss after-hours and overflow calls. Patients hang up, book with a competitor, or show up unprepared.',
    outcomes: [
      '24/7 appointment booking and rescheduling',
      'Symptom intake and smart triage rules',
      'Insurance and eligibility questions handled on the call',
      'Warm transfer to nurses with a live summary',
      'HIPAA-ready encryption, access control, and PII redaction',
    ],
    workflows: [
      'New patient scheduling',
      'Prescription refill requests',
      'After-hours nurse line',
      'Recall and reminder campaigns',
    ],
  },
  {
    slug: 'financial-services',
    name: 'Financial services',
    eyebrow: 'Banks, fintech, and credit unions',
    title: 'Voice AI for banking and fintech that stays inside the rails',
    description:
      'Authenticate callers, resolve account questions, and qualify lending leads with low-latency voice agents built for audit trails and least-privilege access.',
    metric: '60%',
    metricLabel: 'support calls automated',
    pain: 'Call volumes spike around billing cycles and product launches. Human queues grow, while fraud and compliance risk never sleeps.',
    outcomes: [
      'Identity verification and step-up handoff',
      'Balance, payment, and card status conversations',
      'Lead qualification for lending and wealth',
      'Full transcripts for QA and audit',
      'SSO, RBAC, and encryption by default',
    ],
    workflows: [
      'Card lock and unlock requests',
      'Payment reminders',
      'Loan pre-qualification',
      'Branch appointment booking',
    ],
  },
  {
    slug: 'insurance',
    name: 'Insurance',
    eyebrow: 'Carriers, MGAs, and agencies',
    title: 'Claims and policy calls resolved in minutes, not hold queues',
    description:
      'VoilitAI takes first notice of loss, answers coverage questions, and books adjusters — so licensed agents spend time on the cases that need judgment.',
    metric: '5×',
    metricLabel: 'faster claim calls',
    pain: 'FNOL and status calls clog the phone tree. Customers repeat their story three times and still wait for a human.',
    outcomes: [
      'First notice of loss captured structured',
      'Policy and billing FAQs answered instantly',
      'Adjuster and inspection scheduling',
      'Sentiment flags for at-risk customers',
      'Compliant recording and redaction',
    ],
    workflows: [
      'FNOL intake',
      'Renewal outreach',
      'Quote follow-up',
      'Claims status',
    ],
  },
  {
    slug: 'customer-support',
    name: 'Customer support',
    eyebrow: 'SaaS and service brands',
    title: 'A support line that never puts customers on hold',
    description:
      'The most reliable AI customer support line: deflect tickets, keep context across voice and chat, and escalate only when a human should own the outcome.',
    keywords: [
      'most reliable customer support',
      'most reliable AI customer support',
      'AI customer support',
      '24/7 support voice agent',
    ],
    metric: '60%',
    metricLabel: 'inbound automated',
    pain: 'Tier-1 queues are full of password resets, order status, and “where is my…”. Agents burn out. CSAT drops after 5pm.',
    outcomes: [
      'Instant answers from a live knowledge base',
      'Ticket creation with a clean summary',
      'Seamless voice-to-chat continuity',
      'QA on every conversation, not a sample',
      'Languages covered without extra shifts',
    ],
    workflows: [
      'Order and account status',
      'Returns and exchanges',
      'Technical triage',
      'VIP warm transfer',
    ],
  },
  {
    slug: 'lead-qualification',
    name: 'Lead qualification',
    eyebrow: 'Sales and revenue teams',
    title: 'Speed-to-lead that actually picks up the phone',
    description:
      'VoilitAI calls new leads in seconds, qualifies against your rubric, books the meeting, and writes the CRM note before a competitor rings twice.',
    metric: '100×',
    metricLabel: 'faster first contact',
    pain: 'Form fills go cold. SDRs work a stale list. The company that answers within five minutes wins the deal.',
    outcomes: [
      'Inbound and callback in under a minute',
      'Custom qualification questions',
      'Calendar booking on the same call',
      'CRM updates in real time',
      'Outbound reactivation of old leads',
    ],
    workflows: [
      'Web form speed-to-lead',
      'Paid-ad follow-up',
      'Demo booking',
      'No-show recovery',
    ],
  },
  {
    slug: 'home-services',
    name: 'Home services',
    eyebrow: 'HVAC, plumbing, electrical, contractors',
    title: 'The after-hours call that used to go to voicemail becomes a booked job',
    description:
      'Emergency vs routine, dispatch windows, spam filtering, and CRM notes — VoilitAI answers like a trained dispatcher, 24/7.',
    metric: '100%',
    metricLabel: 'of calls answered',
    pain: 'One missed weekend emergency is a four-figure job walking to whoever picked up. Your techs cannot also run the phones.',
    outcomes: [
      'Urgency triage and same-day booking',
      'Spam and robocall filtering',
      'Jobber / Housecall Pro / CRM sync',
      'Confirmation texts from the live call',
      'Outbound reminders that cut no-shows',
    ],
    workflows: [
      'Emergency dispatch',
      'Estimate booking',
      'Membership renewals',
      'Review request follow-up',
    ],
  },
  {
    slug: 'real-estate',
    name: 'Real estate',
    eyebrow: 'Brokerages and property teams',
    title: 'Every listing inquiry answered before the buyer dials the next agent',
    description:
      'Qualify buyers and tenants, book showings, and log every conversation to your CRM — nights and weekends included.',
    metric: '21×',
    metricLabel: 'faster qualification',
    pain: 'Portal leads arrive after hours. By morning they have already toured with someone else.',
    outcomes: [
      'Listing and rental FAQs on demand',
      'Showing and open-house booking',
      'Buyer / renter qualification',
      'Follow Up Boss, kvCore, and GHL sync',
      'Outbound follow-up on stale inquiries',
    ],
    workflows: [
      'Listing inquiry',
      'Rental applications',
      'Open-house RSVP',
      'Sphere-of-influence check-ins',
    ],
  },
  {
    slug: 'legal',
    name: 'Legal',
    eyebrow: 'Law firms and intake teams',
    title: 'Client intake that never misses the call that becomes a case',
    description:
      'Capture conflict-check basics, qualify matters, book consults, and keep privileged conversations inside a controlled environment.',
    metric: '24/7',
    metricLabel: 'intake coverage',
    pain: 'Prospective clients call once. If intake is at lunch, that matter is gone. After-hours PI and family calls are the most expensive ones you miss.',
    outcomes: [
      'Matter-type qualification',
      'Consult scheduling on attorney calendars',
      'Conflict and jurisdiction screening questions',
      'Encrypted transcripts with access control',
      'Warm handoff to a paralegal when needed',
    ],
    workflows: [
      'New-matter intake',
      'Consult booking',
      'Appointment reminders',
      'Referral screening',
    ],
  },
];

export function getSolution(slug) {
  return SOLUTIONS.find((item) => item.slug === slug);
}
